### ISSUE TITLE
Question about `@font-face` usage in "webbuch" stylesheets

### ISSUE THREAD

**Issue by MurakamiShinyu** [Health-Sprints/A-Machine#5]
Unfamiliar `@font-face` syntaxes are used in the "webbuch" stylesheets. What is this `-@font-face`?, and is valid the `font-family` list value in `@font-face {…}`?

e.g.,
https://github.com/akademie-oeffentliches-gesundheitswesen/krisenmanagment/blob/master/webbuch/styles/print.css

```css
@font-face {
    font-family: -apple-system,BlinkMacSystemFont,"noto sans",helvetica neue,helvetica,roboto,segoe ui,arial,sans-serif;
    font-weight : bold;
    font-style: italic;
    src : url(../fonts/NotoSans-BoldItalic.ttf);
}
-@font-face {
    font-family : -apple-system,BlinkMacSystemFont,"noto sans",helvetica neue,helvetica,roboto,segoe ui,arial,sans-serif;
    font-weight : normal;
    font-style: normal;
    src : url(../fonts/NotoSans-Medium.ttf);
}
```

Is the `-` prefix of `-@font-face` to disable the `@font-face` rule?

The `font-family` descriptor in the `@font-face` rule takes single `<family-name>` value in the standard spec https://www.w3.org/TR/css-fonts-3/#font-family-desc ). Why is the list value?
